//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using Unity.Physics;

namespace Unity.Physics.Generated
{
    [BurstCompile]
    public struct UnityPhysicsPhysicsVelocityGhostComponentSerializer
    {
        static GhostComponentSerializer.State GetState()
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds due to TYpeManager not being initialized yet
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 8970840532993740884,
                    ExcludeFromComponentCollectionHash = 0,
                    ComponentType = ComponentType.ReadWrite<Unity.Physics.PhysicsVelocity>(),
                    ComponentSize = UnsafeUtility.SizeOf<Unity.Physics.PhysicsVelocity>(),
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                    ChangeMaskBits = ChangeMaskBits,
                    SendMask = GhostComponentSerializer.SendMask.Predicted,
                    SendToOwner = SendToOwnerType.All,
                    SendForChildEntities = 0,
                    VariantHash = 0,
                    CopyToSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                    CopyFromSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                    RestoreFromBackup =
                        new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                    PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                    CalculateChangeMask =
                        new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                            CalculateChangeMask),
                    Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                    Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                    #if UNITY_EDITOR || DEVELOPMENT_BUILD
                    ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                    #endif
                };
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                s_State.NumPredictionErrorNames = GetPredictionErrorNames(ref s_State.PredictionErrorNames);
                #endif
                s_StateInitialized = true;
            }
            return s_State;
        }
        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;
        public static GhostComponentSerializer.State State => GetState();
        public struct Snapshot
        {
            public int Linear_x;
            public int Linear_y;
            public int Linear_z;
            public int Angular_x;
            public int Angular_y;
            public int Angular_z;
        }
        public const int ChangeMaskBits = 2;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        public static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.Linear_x = (int) math.round(component.Linear.x * 1000);
                snapshot.Linear_y = (int) math.round(component.Linear.y * 1000);
                snapshot.Linear_z = (int) math.round(component.Linear.z * 1000);
                snapshot.Angular_x = (int) math.round(component.Angular.x * 1000);
                snapshot.Angular_y = (int) math.round(component.Angular.y * 1000);
                snapshot.Angular_z = (int) math.round(component.Angular.z * 1000);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        public static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                //Compute the required owner mask for the components and buffers by retrievieng the ghost owner id from the data for the current tick.
                if (snapshotInterpolationData.GhostOwner > 0)
                {
                    var requiredOwnerMask = snapshotInterpolationData.GhostOwner == deserializerState.GhostOwner
                        ? SendToOwnerType.SendToOwner
                        : SendToOwnerType.SendToNonOwner;
                    if ((deserializerState.SendToOwner & requiredOwnerMask) == 0)
                        continue;
                }
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                float snapshotInterpolationFactorRaw = snapshotInterpolationData.InterpolationFactor;
                float snapshotInterpolationFactor = snapshotInterpolationFactorRaw;
                ref var component = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(componentData, componentStride*i);
                component.Linear = new float3(snapshotBefore.Linear_x * 0.001f, snapshotBefore.Linear_y * 0.001f, snapshotBefore.Linear_z * 0.001f);
                component.Angular = new float3(snapshotBefore.Angular_x * 0.001f, snapshotBefore.Angular_y * 0.001f, snapshotBefore.Angular_z * 0.001f);

            }
        }


        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        public static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(backupData, 0);
            component.Linear.x = backup.Linear.x;
            component.Linear.y = backup.Linear.y;
            component.Linear.z = backup.Linear.z;
            component.Angular.x = backup.Angular.x;
            component.Angular.y = backup.Angular.y;
            component.Angular.z = backup.Angular.z;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        public static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.Linear_x = predictor.PredictInt(snapshot.Linear_x, baseline1.Linear_x, baseline2.Linear_x);
            snapshot.Linear_y = predictor.PredictInt(snapshot.Linear_y, baseline1.Linear_y, baseline2.Linear_y);
            snapshot.Linear_z = predictor.PredictInt(snapshot.Linear_z, baseline1.Linear_z, baseline2.Linear_z);
            snapshot.Angular_x = predictor.PredictInt(snapshot.Angular_x, baseline1.Angular_x, baseline2.Angular_x);
            snapshot.Angular_y = predictor.PredictInt(snapshot.Angular_y, baseline1.Angular_y, baseline2.Angular_y);
            snapshot.Angular_z = predictor.PredictInt(snapshot.Angular_z, baseline1.Angular_z, baseline2.Angular_z);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        public static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.Linear_x != baseline.Linear_x) ? 1u : 0;
            changeMask |= (snapshot.Linear_y != baseline.Linear_y) ? (1u<<0) : 0;
            changeMask |= (snapshot.Linear_z != baseline.Linear_z) ? (1u<<0) : 0;
            changeMask |= (snapshot.Angular_x != baseline.Angular_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.Angular_y != baseline.Angular_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.Angular_z != baseline.Angular_z) ? (1u<<1) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 2);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        public static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.Linear_x, baseline.Linear_x, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.Linear_y, baseline.Linear_y, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.Linear_z, baseline.Linear_z, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.Angular_x, baseline.Angular_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.Angular_y, baseline.Angular_y, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.Angular_z, baseline.Angular_z, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        public static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.Linear_x = reader.ReadPackedIntDelta(baseline.Linear_x, compressionModel);
            else
                snapshot.Linear_x = baseline.Linear_x;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.Linear_y = reader.ReadPackedIntDelta(baseline.Linear_y, compressionModel);
            else
                snapshot.Linear_y = baseline.Linear_y;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.Linear_z = reader.ReadPackedIntDelta(baseline.Linear_z, compressionModel);
            else
                snapshot.Linear_z = baseline.Linear_z;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Angular_x = reader.ReadPackedIntDelta(baseline.Angular_x, compressionModel);
            else
                snapshot.Angular_x = baseline.Angular_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Angular_y = reader.ReadPackedIntDelta(baseline.Angular_y, compressionModel);
            else
                snapshot.Angular_y = baseline.Angular_y;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Angular_z = reader.ReadPackedIntDelta(baseline.Angular_z, compressionModel);
            else
                snapshot.Angular_z = baseline.Angular_z;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        public static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<Unity.Physics.PhysicsVelocity>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.Linear, backup.Linear));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.Angular, backup.Angular));
            ++errorIndex;
        }
        public static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("Linear"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("Angular"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}
