//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    public struct PlayerInputSerializer : ICommandDataSerializer<PlayerInput>
    {
        public void Serialize(ref DataStreamWriter writer, in PlayerInput data)
        {
            writer.WriteFloat(data.Movement.x);
            writer.WriteFloat(data.Movement.y);
            writer.WriteFloat(data.Jump);
        }

        public void Deserialize(ref DataStreamReader reader, ref PlayerInput data)
        {
            data.Movement.x = reader.ReadFloat();
            data.Movement.y = reader.ReadFloat();
            data.Jump = reader.ReadFloat();
        }

        public void Serialize(ref DataStreamWriter writer, in PlayerInput data, in PlayerInput baseline, NetworkCompressionModel compressionModel)
        {
            writer.WritePackedFloatDelta(data.Movement.x, baseline.Movement.x, compressionModel);
            writer.WritePackedFloatDelta(data.Movement.y, baseline.Movement.y, compressionModel);
            writer.WritePackedFloatDelta(data.Jump, baseline.Jump, compressionModel);
        }

        public void Deserialize(ref DataStreamReader reader, ref PlayerInput data, in PlayerInput baseline, NetworkCompressionModel compressionModel)
        {
            data.Movement.x = reader.ReadPackedFloatDelta(baseline.Movement.x, compressionModel);
            data.Movement.y = reader.ReadPackedFloatDelta(baseline.Movement.y, compressionModel);
            data.Jump = reader.ReadPackedFloatDelta(baseline.Jump, compressionModel);
        }
    }
    public class PlayerInputSendCommandSystem : CommandSendSystem<PlayerInputSerializer, PlayerInput>
    {
        [BurstCompile]
        struct SendJob : IJobEntityBatch
        {
            public SendJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendJob{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
    public class PlayerInputReceiveCommandSystem : CommandReceiveSystem<PlayerInputSerializer, PlayerInput>
    {
        [BurstCompile]
        struct ReceiveJob : IJobEntityBatch
        {
            public ReceiveJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var recvJob = new ReceiveJob{data = InitJobData()};
            ScheduleJobData(recvJob);
        }
    }
}
